server:
  port: 8100

spring:
  application:
    name: send-whatsapp
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL}
    producer:
      bootstrap-servers: ${KAFKA_URL}


app:
  whatsapp:
    instance: ${INSTANCE_ZAPI}
    token: ${TOKEN_ZAPI}
