spring:
  application:
    name: envioMensagemEmail
# Configurações do Kafka
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092}
# Configurações do banco de dados
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/sendMessageEmail}
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true