spring:
  application:
    name: envioMensagemEmail

# Configuracoes do Kafka
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}

# Configuracoes do banco de dados
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true